#!/usr/bin/env node
// SSOT: REDACT_PATTERNS in packages/core/src/audit/service.ts → README ASI06 block.
// Run: `pnpm sync:readme` (write) or `pnpm sync:readme --check` (CI drift check).
//
// Replaces content between
//   <!-- generated:asi06-patterns:start -->
//   <!-- generated:asi06-patterns:end -->
// in README.md so README and code never drift.

import { readFileSync, writeFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const repoRoot = resolve(here, '..')
const SERVICE_PATH = resolve(repoRoot, 'packages/core/src/audit/service.ts')
const README_PATH = resolve(repoRoot, 'README.md')

const START = '<!-- generated:asi06-patterns:start -->'
const END = '<!-- generated:asi06-patterns:end -->'

const checkMode = process.argv.includes('--check')

// --- Extract REDACT_PATTERNS array literal from service.ts -----------
function extractPatterns() {
  const source = readFileSync(SERVICE_PATH, 'utf8')
  // Anchor on `\n]\nconst` (the array's closing bracket on its own line,
  // followed by the next top-level statement) so `]` characters inside
  // regex character classes don't terminate the match early.
  const match = source.match(/const REDACT_PATTERNS:\s*RegExp\[\]\s*=\s*\[([\s\S]*?)\n\]\nconst/)
  if (!match) {
    throw new Error(`REDACT_PATTERNS array not found in ${SERVICE_PATH}`)
  }
  const body = match[1]
  // Each entry: "  /regex/flags, // optional comment"
  // We capture the raw regex source + the trailing comment (used as label).
  const entries = []
  for (const line of body.split('\n')) {
    const m = line.match(/^\s*\/(.+?)\/[a-z]*,?\s*(?:\/\/\s*(.+?))?\s*$/)
    if (!m) continue
    entries.push({ regex: m[1], comment: m[2]?.trim() ?? '' })
  }
  if (entries.length === 0) {
    throw new Error('REDACT_PATTERNS body parsed to zero entries')
  }
  return entries
}

// --- Render markdown block ------------------------------------------
function renderBlock(entries) {
  const lines = []
  lines.push(START)
  lines.push('')
  lines.push('<!-- DO NOT EDIT — generated by `pnpm sync:readme` from packages/core/src/audit/service.ts -->')
  lines.push('')
  lines.push('| # | Regex source | Note |')
  lines.push('|---|--------------|------|')
  entries.forEach((e, i) => {
    const note = e.comment.length > 0 ? e.comment : '—'
    lines.push(`| ${i + 1} | \`/${e.regex}/\` | ${note} |`)
  })
  lines.push('')
  lines.push(END)
  return lines.join('\n')
}

// --- Splice into README ---------------------------------------------
function spliceBlock(readme, block) {
  const startIdx = readme.indexOf(START)
  const endIdx = readme.indexOf(END)
  if (startIdx === -1 || endIdx === -1) {
    throw new Error(
      `README is missing ${START} / ${END} markers. ` +
      `Add them between paragraphs in the ASI06 section.`
    )
  }
  if (endIdx < startIdx) {
    throw new Error('marker order inverted in README')
  }
  const before = readme.slice(0, startIdx)
  const after = readme.slice(endIdx + END.length)
  return before + block + after
}

// --- Main -----------------------------------------------------------
const entries = extractPatterns()
const block = renderBlock(entries)
const readme = readFileSync(README_PATH, 'utf8')
const next = spliceBlock(readme, block)

if (next === readme) {
  console.log(`README is in sync (${entries.length} patterns)`)
  process.exit(0)
}

if (checkMode) {
  console.error('README drift detected: run `pnpm sync:readme` and commit')
  process.exit(1)
}

writeFileSync(README_PATH, next, 'utf8')
console.log(`README updated (${entries.length} patterns)`)
